all: SyncProducer  SyncConsumer

SyncProducer: SyncProducer.java
	javac -Xlint -cp "/usr/local/kafka/libs/*" SyncProducer.java

SyncConsumer: SyncConsumer.java
	javac -Xlint -cp "/usr/local/kafka/libs/*" SyncConsumer.java
